<?php 
public function test()
{
	$coop = (object) array(

		'faculty_id'=>'',
		'lang'=>'',
		'name_and_surname_thai_1'=>'',
		'major_year_1'=>'',
		'year_1'=>'',
		'advisor_name_1'=>'',
		'faculty_1'=>'',
		'name_and_surname_eng_1'=>'',
		'major_year_eng_1'=>'',
		'year_1'=>'',
		'advisor_name_eng_1'=>'',
		'faculty_eng_1'=>'',
		'student_id_1'=>'',
		'phone_number_1'=>'',
		'semester_gpa_1'=>'',
		'cumulative_gpa_1'=>'',
		'email_1'=>'',
		'working_from_1'=>'',
		'working_until_1'=>'',
		'period_of_working_1_1'=>'',
		'position_1_2'=>'',
		'oraganization_name_1_2'=>'',
		'period_of_working_1_2'=>'',
		'course_1_1'=>'',
		'course_1_2'=>'',
		'course_duration_1_1'=>'',
		'course_duration_1_2'=>'',
		'course_gpa_1_1'=>'',
		'course_gpa_1_2'=>'',
		'identification_card_no_1'=>'',
		'issued_at_1'=>'',
		'issued_date_1'=>'',
		'expiry_date_1'=>'',
		'race_1'=>'',
		'nationality_1'=>'',
		'religion_1'=>'',
		'date_of_birth_1'=>'',
		'place_of_birth_1'=>'',
		'sex_1'=>'',
		'height_1'=>'',
		'weight_1'=>'',
		'chronical_disease_1'=>'',

		'address_this_term_2'=>'',
		'tel_2_1'=>'',
		'moblie_2_1'=>'',
		'fax_2_1'=>'',
		'email_2'=>'',

		'permanent_address_2'=>'',
		'tel_2_2'=>'',		
		'moblie_2_2'=>'',
		'fax_2_2'=>'',

		'name_emergency_2'=>'',
		'relation_emergency_2'=>'',
		'occupation_emergency_2'=>'',
		'place_of_work_emergency_2'=>'',
		'address_emergency_2'=>'',
		'tel_emergency_2'=>'',
		'fax_emergency_2'=>'',
		'email_emergency_2'=>'',

		'father_name_2'=>'',
		'age_father_2'=>'',
		'occupation_father_2'=>'',
		'address_father_2'=>'',
		'moo_father_2'=>'',
		'soi_father_2'=>'',
		'sub_district_father_2'=>'',
		'district_father_2'=>'',
		'province_father_2'=>'',
		'zip_cord_father_2'=>'',
		'tel_father_2'=>'',
		'fax_father_2'=>'',
		'email_father_2'=>'',

		'mother_name_2'=>'',
		'age_mother_2'=>'',
		'occupation_mother_2'=>'',
		'address_mother_2'=>'',
		'moo_mother_2'=>'',
		'soi_mother_2'=>'',
		'sub_district_mother_2'=>'',
		'district_mother_2'=>'',
		'province_mother_2'=>'',
		'zip_cord_mother_2'=>'',
		'tel_mother_2'=>'',
		'fax_mother_2'=>'',
		'email_mother_2'=>'',

		'no_of_relatives_2'=>'',
		'you_are_the_2'=>'',

		'name_relatives_2_1'=>'',
		'age_relatives_2_1'=>'',
		'occupation_relatives_2_1'=>'',
		'position_relatives_2_1'=>'',
		'address_relatives_2_1'=>'',

		'name_relatives_2_2'=>'',
		'age_relatives_2_2'=>'',
		'occupation_relatives_2_2'=>'',
		'position_relatives_2_2'=>'',
		'address_relatives_2_2'=>'',

		'name_relatives_2_3'=>'',
		'age_relatives_2_3'=>'',
		'occupation_relatives_2_3'=>'',
		'position_relatives_2_3'=>'',
		'address_relatives_2_3'=>'',

		'name_relatives_2_4'=>'',
		'age_relatives_2_4'=>'',
		'occupation_relatives_2_4'=>'',
		'position_relatives_2_4'=>'',
		'address_relatives_2_4'=>'',

		'name_relatives_2_5'=>'',
		'age_relatives_2_5'=>'',
		'occupation_relatives_2_5'=>'',
		'position_relatives_2_5'=>'',
		'address_relatives_2_5'=>'',

		'primary_name_3'=>'',
		'primary_province_3'=>'',
		'primary_year_attended_3'=>'',
		'primary_year_graduated_3'=>'',
		'primary_major_3'=>'',

		'secondary_name_3'=>'',
		'secondary_province_3'=>'',
		'secondary_year_attended_3'=>'',
		'secondary_year_graduated_3'=>'',
		'secondary_major_3'=>'',

		'high_school_name_3'=>'',
		'high_school_province_3'=>'',
		'high_school_year_attended_3'=>'',
		'high_school_year_graduated_3'=>'',
		'high_school_major_3'=>'',

		'university_name_3'=>'',
		'university_province_3'=>'',
		'university_year_attended_3'=>'',
		'university_year_graduated_3'=>'',
		'university_major_3'=>'',

		'previous_training_year_from_3'=>'',
		'previous_training_year_to_3'=>'',
		'previous_training_jobdescription_3'=>'',
		'previous_training_organization_3'=>'',
		'previous_training_province_3'=>'',

		'career_objectives_3_1'=>'',
		'career_objectives_3_2'=>'',
		'career_objectives_3_3'=>'',
		'career_objectives_3_4'=>'',

		'student_activities_year_4_1'=>'',
		'student_activities_position_4_1'=>'',
		'student_activities_year_4_2'=>'',
		'student_activities_position_4_2'=>'',
		'student_activities_year_4_3'=>'',
		'student_activities_position_4_3'=>'',

		'english_listening_4'=>'',
		'english_speaking_4'=>'',
		'english_reading_4'=>'',
		'english_writing_4'=>'',

		'chinese_listening_4'=>'',
		'chinese_speaking_4'=>'',
		'chinese_reading_4'=>'',
		'chinese_writing_4'=>'',

		'other_language_4'=>'',

		'other_listening_4'=>'',
		'other_speaking_4'=>'',
		'other_reading_4'=>'',
		'other_writing_4'=>'',

		'special_ability_4_1'=>'',
		'special_ability_4_2'=>'',
		'special_ability_4_3'=>'',
		'computerized_ability_4_1'=>'',
		'car_license_no_4_1'=>'',
		'motorcycle_license_no_4_1'=>'',
		'sport_4_1'=>'',
		'hobbies_4_1'=>'',

		'explain_about_yourself'=>'',

		
	);

	$data =array('coop0103'=>$coop);
	$this->load->view('coop0103PDF',$data);
}
?>